version = 1
SPDX-PackageName = "Tabularius"
SPDX-PackageSupplier = "Friedrich von Never <friedrich@fornever.me>"
SPDX-PackageDownloadLocation = "https://github.com/ForNeVeR/tabularius"

[[annotations]]
path = "*.DotSettings"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025-2026 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"
